### ISSUE TITLE
Library – add 'Imprint Statement' to LO

### ISSUE THREAD

**Issue by brutaldigital** [digirati-co-uk/pmc-lux#1]
PMC example: https://lux-front-sbx.collections.yale.edu/view/text/96d4e28a-decd-4d03-8f12-15d0ae05305d
e.g. record ID 1474407161 

```
    <place>Edinburgh</place>
    <publisher>Edinburgh University Press</publisher>
    <year>2018</year>
```

YUL example: https://lux-front-sbx.collections.yale.edu/view/text/5b6afc6d-16c8-4685-9663-3b7412de441f
Recipe from YUL: https://linked-art.library.yale.edu/node/67abd2f7-5011-49fd-b8b5-e1da1795ed0e

```
{
"type": "LinguisticObject",
"content": "Edinburgh : Edinburgh University Press, [2018]",
"classified_as": [
{
"id": "http://vocab.getty.edu/aat/300202362",
"type": "Type",
"_label": "Imprint Statement",
"classified_as": [
{
"id": "http://vocab.getty.edu/aat/300418049",
"type": "Type",
"_label": "Brief Text"
}
]
}
]
}
```

**Comment by tomcrane** [comment]
Would this always be simply

`{place} : {publisher}, [{year}]`

(with some guards against any of them being missing)?

**Comment by tomcrane** [comment]
https://github.com/tomcrane/linked-art-net/commit/7f220cc0afe1ff109c160507be6debee7aa3c25a
