### ISSUE TITLE
Library – include DigitalObject 

### ISSUE THREAD

**Issue by brutaldigital** [digirati-co-uk/pmc-lux#10]
Would it be possible to extract URLs from the `afilecsvx` field?

Record ID W67
` <afilecsvx>https://www.thomasgirtin.com/ [AVAILABLE ON THE WWW. CLICK HERE TO ACCESS]||</afilecsvx>
`

See
https://lux-front-sbx.collections.yale.edu/view/digital/4e34c3ed-94a0-47bf-904c-fadf2bbcdba6

```json
"subject_of": [
{
"type": "LinguisticObject",
"_label": "Text of Digital Asset Page",
"digitally_carried_by": [
{
"type": "DigitalObject",
"_label": "Digital Asset Page",
"identified_by": [
{
"type": "Name",
"content": "Online book",
"classified_as": [
{
"id": "http://vocab.getty.edu/aat/300404669",
"type": "Type",
"_label": "Display Title"
}
]
}
],
"access_point": [
{
"id": "https://yale.idm.oclc.org/login?URL=https://link.gale.com/apps/doc/PNGVON526946977/MOME?sid=gale_marc&u=29002",
"type": "DigitalObject",
"_label": "Access Point"
}
]
}
]
},
```

**Comment by tomcrane** [comment]
hmm that should be happening 
https://github.com/tomcrane/linked-art-net/blob/pmc/LinkedArt/PmcTransformer/Library/Helpers.cs#L204

(related to #11)
It is not super common but there are quite a few of them, e.g., 

In 
```
    {
      "type": "LinguisticObject",
      "content": "\u003Cspan class=\u0022lux_data\u0022\u003E\u003Ca href=\u0022https://www.aaeportal.com/?id=-19393\u0022\u003EE-book available via the A\u0026AePortal link. Access only available to in person visitors\u003C/a\u003E\u003C/span\u003E",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300133046",
          "type": "Type",
          "_label": "Access Statement"
        }
      ]
    }
```

I can't see it in https://lux-front-sbx.collections.yale.edu/data/object/607f1229-dde0-4dc4-befe-8c0f455cd633 though

**Comment by tomcrane** [comment]
Is the unicode escaping throwing it?

**Comment by brutaldigital** [comment]
Appearing on the work in right-hand panel
