### ISSUE TITLE
All – add "How do I see it?" statement to LO

### ISSUE THREAD

**Issue by brutaldigital** [digirati-co-uk/pmc-lux#11]
All data should be accompanied by a "How do I see it?" statement. See https://ycba-lux.s3.amazonaws.com/v3/object/95/954d01f0-d95c-4fb0-9131-be4841ffb3e1.json

The PMC's statement should read something like:

"The Paul Mellon Centre’s Archives and Library collections are open to everyone and there is no charge for accessing the materials. They are based in London, UK, and we offer an in person visits, remote enquiries, and a copying service.h ttps://www.paul-mellon-centre.ac.uk/archives-and-library/visiting-the-public-study-room"

Model:

```json
{
"type": "LinguisticObject",
"classified_as": [
{
"id": "http://vocab.getty.edu/aat/300133046",
"type": "Type",
"_label": "Access Statement",
"classified_as": [
{
"id": "http://vocab.getty.edu/aat/300418049",
"type": "Type",
"_label": "Brief Text"
}
]
}
],
"content": "On view at the Yale University Art Gallery"
},
```

FYI, hyperlinks links should be encoded following this patter:

`"content":" <a href='**LINK**'> **Your text for link here** </a>"`

**Comment by tomcrane** [comment]
Each archive xml record that has the field `<AccessConditions>` gets its value of that field applied as the Access statement:

e.g., https://data.paul-mellon-centre.ac.uk/archive/09b93c0e-e5dc-4b07-95ce-99ec42a16c72

```
...
{
      "type": "LinguisticObject",
      "content": "This collection is open for research. Readers must fill in an \u0027Reader Agreement Form\u0027 which outlines the reading room rules and conditions concerning privacy and Data Protection",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300133046",
          "type": "Type",
          "_label": "Access Statement",
          "classified_as": [
            {
              "id": "http://vocab.getty.edu/aat/300418049",
              "type": "Type",
              "_label": "Brief Text"
            }
          ]
        }
      ]
    }
...
    ```

I could add this additional statement where one already exists (rather than replace that one)

Also for library should this be applied to the HumanMadeObjects only (which can be seen), or the LinguisticObjects as well?


 - add this additional one where

**Comment by tomcrane** [comment]
https://github.com/tomcrane/linked-art-net/commit/15ba95a925531f22c813c6527b55183e4f2313f6
