### ISSUE TITLE
Archives – Add sort identifier to archives to ensure explore list is in the right order

### ISSUE THREAD

**Issue by brutaldigital** [digirati-co-uk/pmc-lux#14]
Single digit numbers references are displaying out of order. E.g. 

BS/6/1/1 - Hieronymous Bosch  
BS/6/1/10 - David Hockney 
BS/6/1/11 - Post-war artists 

Ordering of sets should use record ID as sort value. 

```json
{
"type": "Identifier",
"content": "000001f40002fda0",
"classified_as": [
{
"id": "https://vocab.getty.edu/aat/300451544",
"type": "Type",
"_label": "Sort Name"
}
],
"assigned_by": [
{
"type": "AttributeAssignment",
"motivated_by": [
{
"id": "https://linked-art.library.yale.edu/node/b95ab112-61ec-455e-ba54-949433b69ca6",
"type": "Set",
"_label": "Series I: Correspondence, 1917-1979"
}
]
}
]
}
```

**Comment by azaroth42** [comment]
This one is a vocabulary synchronization issue. YUL's archive uses an older identifier, so that's what the code checks for. We've asked YUL to update to the newer AAT which you already use.

So this can be closed -- it'll fix itself as soon as YUL updates.

**Comment by azaroth42** [comment]
Fixed: https://lux-front-sbx.collections.yale.edu/view/set/1b1e6ec4-b01e-4f48-a0f1-e98f489ea280
