### ISSUE TITLE
Archives – confirm correct 'Categorized As' type

### ISSUE THREAD

**Issue by brutaldigital** [digirati-co-uk/pmc-lux#19]
Rob, 

PMC Archive collection records appear to either be classified as "Archives" (see https://lux-front-sbx.collections.yale.edu/view/set/7aaacfd9-3df5-4e79-8355-71946a1e2085) or "Physical Objects" (see https://lux-front-sbx.collections.yale.edu/view/object/ce373124-a009-42cc-a5bc-81c59ee6556b)

Yale archive collections use the categorisation "archival materials" (see https://lux-front-sbx.collections.yale.edu/view/object/647f74c4-338f-400a-a2c2-0f0cf3a97722).

Which is preferred?

**Comment by azaroth42** [comment]
HMOs from the archive should have a classified_as of archival materials, yes.

The class of "Physical Object" is just that it's an HMO, rather than a Digital Object.

**Comment by tomcrane** [comment]
Current logic 
https://github.com/tomcrane/linked-art-net/blob/pmc/LinkedArt/PmcTransformer/Archive/Helpers.cs#L24

All Sets are "archives (groupings)", https://vocab.getty.edu/aat/300375748
HMOs with level Item are all "Archival Materials", https://vocab.getty.edu/aat/300379505

Sets with level **Sub-Series** are additionally https://vocab.getty.edu/aat/300404023
Sets with level **Series** are additionally https://vocab.getty.edu/aat/300404022
Sets with level **Collection** are additionally https://vocab.getty.edu/aat/300025976

So I think I am emitting the right stuff? I don't see "Archives" or "Physical Objects" in the two linked resources in the description.

**Comment by tomcrane** [comment]
https://github.com/tomcrane/linked-art-net/commit/ad256964d8f69765f6b7aa01f070ec58f475e610
