### ISSUE TITLE
Archives – confirm Fonds record designation HMO / LO?

### ISSUE THREAD

**Issue by brutaldigital** [digirati-co-uk/pmc-lux#20]
Rob,

PMC archive records for Fonds-level descriptions are classified as 'Works' in search, but equivalent Fonds-level records from the Beinecke are classified as 'Objects'.

- PMC, Benedict Nicolson papers: https://lux-front-sbx.collections.yale.edu/view/set/90b0968b-0f8f-4245-87d0-1c50b41c7479
- Beinecke, Vita Sackville-West papers: https://lux-front-sbx.collections.yale.edu/view/set/ee9f4172-dcd0-431c-88c6-8cb3a7ae56f1

Which is the preferred classification?

**Comment by azaroth42** [comment]
Both of those should be filed under Works -- they're the intellectual arrangement of the papers, not the physical papers themselves.
