### ISSUE TITLE
Library – (NUM) note missing

### ISSUE THREAD

**Issue by brutaldigital** [digirati-co-uk/pmc-lux#7]
NUM note is missing from library records e.g. Record ID ZB3557

https://lux-front-sbx.collections.yale.edu/view/text/32331848-40b4-404c-bc58-2fec89e21cb6

Note from PMC / LUX Data Transformation doc:
> 'NUM': Numbers borne by the item (e.g. auction catalogs) ignore for now
> Future work to figure out auction catalogs better

This data is useful for remote enquiries as it refers to a specific volume within a bound set – would it be possible to re-introduce it?

**Comment by azaroth42** [comment]
I think discuss in person on Oct 21?
