### ISSUE TITLE
Library – CLASS = 'AUCTION CATALOGUE'

### ISSUE THREAD

**Issue by brutaldigital** [digirati-co-uk/pmc-lux#8]
Rob,

In the PMC / LUX Data Transformation doc you noted

> If the value is "AUCTION CATALOGUES", or starts with "IN PROCESS",  then ignore. Otherwise, an identifier for the Object.

However, this has resulted in a partial representation in the LUX data.

Record ID S5719 (the LO) is omitted with this rule, but record ID S164 (the HMO) is included https://lux-front-sbx.collections.yale.edu/view/object/589adb66-e995-4ad4-b59a-83e947c42beb

**Comment by azaroth42** [comment]
Ahh :( Yes, if the LO is excluded then then the HMO should be excluded as well.

**Comment by tomcrane** [comment]
Neither are excluded from the export though - it just means the value of `<class>` is ignored in the processing.

[/library/work/S5719.json](https://github.com/user-attachments/files/17256078/S5719.json)
[/library/object/S164/accno_B15132.json](https://github.com/user-attachments/files/17256087/accno_B15132.json)

the latter `carries` the former - this is S5719 - https://lux-front-sbx.collections.yale.edu/view/text/49b7dfdc-a8e9-40ce-a27e-1e1a96af426a

https://lux-front-sbx.collections.yale.edu/data/text/49b7dfdc-a8e9-40ce-a27e-1e1a96af426a is carried by https://lux-front-sbx.collections.yale.edu/data/object/589adb66-e995-4ad4-b59a-83e947c42beb

**Comment by brutaldigital** [comment]
Invalid
