### ISSUE TITLE
Library – revisit decision to exclude "IN PROCESS"

### ISSUE THREAD

**Issue by brutaldigital** [digirati-co-uk/pmc-lux#9]
My colleagues tell me that up to 20% of library stock is 'in process'.

We previously decided to omit those records from the LUX export. As this is a significant portion of the collection should that decision be revisited?

NB records with `<class>IN PROCESS - SEWELL</class>` are not being excluded and some examples include a good amount of data https://lux-front-sbx.collections.yale.edu/view/text/bee49bce-6fa9-4569-ac83-9c2644883497

**Comment by azaroth42** [comment]
20%, ouch. Discuss on Oct 21?

**Comment by brutaldigital** [comment]
To be included
